apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: finops-demo
data:
  otel-collector-config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: ""
        metric_expiration: 5m

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          exporters: [prometheus]