apiVersion: batch/v1
kind: Job
metadata:
  name: finops-seeder
  namespace: finops-demo
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: finops-seeder
          image: ghcr.io/filipdadgar/fd_finopsdemo:main
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_MODE
              value: seed
            - name: DEMO_RANDOM_SEED
              value: "42"