apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: finops-demo

resources:
  - namespace.yaml
  - configmap-prometheus.yaml
  - configmap-otel-collector.yaml
  - configmap-grafana-datasource.yaml
  - pvc-prometheus.yaml
  - pvc-grafana.yaml
  - job-finops-seeder.yaml
  - deployment-otel-collector.yaml
  - service-otel-collector.yaml
  - deployment-finops-exporter.yaml
  - service-finops-exporter.yaml
  - deployment-prometheus.yaml
  - service-prometheus.yaml
  - deployment-grafana.yaml
  - service-grafana.yaml